# Generated by Django 5.0.1 on 2024-03-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completedTutorial',
            field=models.BooleanField(default=False),
        ),
    ]
