# Generated by Django 5.0.1 on 2024-03-18 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_completedtutorial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
