# Generated by Django 5.0.1 on 2024-03-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='incorrectQuestions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quizQuestionsTotal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='revised',
            field=models.BooleanField(default=False),
        ),
    ]
