# Generated by Django 5.0.1 on 2024-03-15 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_quiz_correctlyanswered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='revised',
        ),
    ]
